import type { Metadata } from 'next';

import '@/app/globals.css';
import Link from 'next/link';
import localFont from 'next/font/local';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' });

const myFont = localFont({
  src: [
    {
      path: './font/ZhiyongDatongFont.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-ZhiyongDatongFont',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  team,
  analysis,
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analysis: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${myFont.variable} ${inter.variable}`}>
      <body className="min-h-full flex flex-col">
        <div className={inter.className}>这是google font
          <div className={`${myFont.className}`}>这是Hahha</div>
        </div>
        <div className="font-aa">我想自定义一下</div>
       
        {children}
      </body>
    </html>
  );
}
